title: Tania Ghosh # your name (or website title) here
logo: "/images/TaniaGhosh.jpg ? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  EMPOWERING DECISIONS WITH DATA, INNOVATIONS AND CLEAR COMMUNICATIONS
  <br><br>
  Result-oriented Data Scientist with four years of experience in predictive analytics and statistical modeling with a strong track record of developing and implementing cutting-edge models and algorithms. Skilled in leveraging data-driven insights to drive business growth and optimize ley metrics, including customer retention, fraud detection, and revenue generation. Collaborative team player with a passion for innovation, excellent communications skills, and proven ability to deliver impactful solutions in fast-paced environments
  <br><br>
  <a href="https://www.linkedin.com/in/tghosh2020/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
